#!/bin/sh
#python /home/bjornar/MScDissertation/FacExpRec/FER2013_train_and_predict/CNN_FaceExp/binaryClassification/train_FER2013_binary.py train firstRev
#python /home/bjornar/MScDissertation/FacExpRec/FER2013_train_and_predict/CNN_FaceExp/binaryClassification/train_FER2013_binary.py train secondRev
python /home/bjornar/MScDissertation/FacExpRec/FER2013_train_and_predict/CNN_FaceExp/binaryClassification/train_FER2013_binary.py train seventhRev
python /home/bjornar/MScDissertation/FacExpRec/FER2013_train_and_predict/CNN_FaceExp/binaryClassification/train_FER2013_binary.py train eigthRev
python /home/bjornar/MScDissertation/FacExpRec/FER2013_train_and_predict/CNN_FaceExp/binaryClassification/train_FER2013_binary.py train ninthRev

